CREATE DATABASE [Service]
USE [Service]

DROP DATABASE [Service]


CREATE TABLE Users
(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	Username VARCHAR(30) UNIQUE NOT NULL,
	[Password] VARCHAR(50) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	Birthdate DATETIME NOT NULL,
	Age INT ,
	CHECK(Age >= 14 AND Age <= 110),
	Email VARCHAR(50) NOT NULL
)

CREATE TABLE Departments
(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
)

CREATE TABLE Employees
(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	FirstName VARCHAR(25),
	LastName VARCHAR(25),
	Birthdate DATETIME,
	Age INT,
	CHECK(Age >= 14 AND Age <= 110),
	DepartmentId INT REFERENCES Departments(Id)
)

CREATE TABLE Categories
(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	DepartmentId INT NOT NULL REFERENCES Departments(Id)
)

CREATE TABLE [Status]
(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	[Label] VARCHAR(30) NOT NULL,
)

CREATE TABLE Reports
(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	CategoryId INT NOT NULL REFERENCES Categories(Id),
	StatusId INT NOT NULL REFERENCES [Status](Id),
	OpenDate DATETIME NOT NULL,
	CloseDATE DATETIME ,
	[Description] VARCHAR(200) NOT NULL,
	UserId INT NOT NULL REFERENCES [Users] (Id),
	EmployeeId INT REFERENCES [Employees](Id)
)