CREATE DATABASE OnlineStore
USE OnlineStore

CREATE TABLE Cities
(
	CityID INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL
)
CREATE TABLE Customers
(
	CustomerID INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50),
	Birthday DATE,
	CityID INT,
)
ALTER TABLE Customers
	ADD FOREIGN KEY (CityID) REFERENCES Cities(CityID)

CREATE TABLE Orders
(
	OrderID INT NOT NULL PRIMARY KEY,
	CustomerID INT NOT NULL,
)
ALTER TABLE Orders
	ADD FOREIGN KEY	(CustomerID) REFERENCES Customers(CustomerID)


CREATE TABLE ItemTypes
(
	ItemTypeID INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL
)
CREATE TABLE Items
(
	ItemID INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(30) NOT NULL,
	ItemTypeID INT NOT NULL, 
)
ALTER TABLE Items
	ADD FOREIGN KEY (ItemTypeID) REFERENCES ItemTypes(ItemTypeID)

CREATE TABLE OrderItems
(
	OrderID INT NOT NULL,
	ItemID INT NOT NULL
	PRIMARY KEY (OrderID, ItemID)
)
ALTER TABLE OrderItems
	ADD FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)

ALTER TABLE OrderItems
	ADD FOREIGN KEY (ItemID) REFERENCES Items(ItemID)