CREATE DATABASE University 
USE University

CREATE TABLE Majors
(
	MajorID INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(30) NOT NULL,
)
CREATE TABLE Students
(
	StudentID INT NOT NULL PRIMARY KEY,
	StudentNumber INT NOT NULL,
	StudentName VARCHAR(30),
	MajorID INT NOT NULL
)
ALTER TABLE Students
	ADD FOREIGN KEY (MajorID) REFERENCES Majors(MajorID)

CREATE TABLE Payments
(
	PaymetID INT NOT NULL PRIMARY KEY,
	PaymentDate DATE NOT NULL,
	PaymentAmaout DECIMAL,

	StudentID INT NOT NULL,
	FOREIGN KEY (StudentID) REFERENCES Students (StudentID)
)

CREATE TABLE Subjects
(
	SubjectID INT NOT NULL PRIMARY KEY,
	SubjectName INT NOT NULL,
)

CREATE TABLE Agenda
(
	StudentID INT NOT NULL,
	SubjectID INT NOT NULL,
	PRIMARY KEY (StudentID, SubjectID)
)
ALTER TABLE Agenda
	ADD FOREIGN KEY (StudentID) REFERENCES Students(StudentID)
ALTER TABLE Agenda
	ADD FOREIGN KEY (SubjectID) REFERENCES Subjects(SubjectID)